version: '3.3'
services:
  postgres:
    container_name: postgres-film
    image: postgres
    ports:
      - 5460:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: film_db
    networks:
      - film
  
  php-fpm:
    container_name: php-fpm-film
    build:
      context: ./build/php-fpm
      dockerfile: Dockerfile
      args:
        - XDEBUG_MODE
        - XDEBUG_CLIENT_HOST
    environment:
      - SYMFONY_ENV
      - PHP_IDE_CONFIG
    command: sh -c "composer install && php bin/console doctrine:migration:migrate --no-interaction && php-fpm"
    ports:
      - 9612:9000
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./logs/symfony:/var/www/symfony/var/log:cached
      - ./film/:/var/www/film/:delegated
    depends_on:
      - postgres
    networks:
      - film
  
  nginx:
    image: nginx:latest
    container_name: nginx-film
    ports:
      - 8560:80
    depends_on:
      - php-fpm
    networks:
      - film
    volumes:
      - ./build/nginx/local:/etc/nginx/conf.d/
      - ./build/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
      - ./film/public:/var/www/film/public:rw,cached

networks:
  film:
