nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN_HTTPS)%', '%env(CORS_ALLOW_ORIGIN_HTTP)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Access-Control-Allow-Origin', 'Authorization', 'token']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
